apiVersion: apps/v1
kind: Deployment
metadata:
  name: codecanvas-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codecanvas-frontend
  template:
    metadata:
      labels:
        app: codecanvas-frontend
    spec:
      containers:
        - name: frontend
          image: codecanvas-frontend:latest # This is the Docker image name
          ports:
            - containerPort: 80
