apiVersion: v1
kind: Service
metadata:
  name: codecanvas-frontend-service
spec:
  type: NodePort
  selector:
    app: codecanvas-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
